# Generated by Django 5.2.15 on 2026-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
